version: "3.9"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - allgalleries
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - allgalleries
    volumes: 
      - "./mongoData:/data/db"

networks:
  allgalleries:
